#!/bin/sh
#
# Copyright (C) 2016-2017, Nanjing StarOS Technology Co., Ltd
#
CURRENT=`pwd`
export ROOTDIR=$CURRENT/../

export STAROSCONTROLLER_ROOT=$ROOTDIR

export USER_ROOT=$CURRENT/../

export BUILD_NUMBER=1

export STAROSCONTROLLER_VERSION="1.2.0"

export STAROSCONTROLLER_STAGE_ROOT=/tmp
export STAROSCONTROLLER_RPM_ROOT=$STAROSCONTROLLER_STAGE_ROOT/rpm
export STAROSCONTROLLER_RPM_VERSION=${STAROSCONTROLLER_VERSION//-/.}
export STAROSCONTROLLER_STAGE=$CURRENT/staroscontroller




