export STARDLLS_VERSION=1.4.2
export PROTOCOL_VERSION=1.2.3
export STARLANG_VERSION=1.3.2
export DIPC_VERSION=1.5.2
export STARCORE_VERSION=1.4.0
export DPDK_VERSION=16.11.0
export STARFACE_VERSION=1.2.0
export STARFACE_NAME=tunpeer
export STARONOS_VERSION=1.8.2
export STAROS_VERSION=1.1.0
export STAROSCONTROLLER_VERSION=1.2.0
export STARFACESERVER_VERSION=1.2.2

